Fix for builds on macOS.
There exists a conflict between BLAS included in the Accelerate
framework and in GSL. Errors like those shown below when compiling
against libmdb_matrix before this "fix." The fix assumes that the GSL
BLAS enumerations and so forth are defined identically to those in
Accelerate (they should be, but who knows). It's unclear why there is
BLAS definition contention on macOS (and homebrew GSL).

In file included from ./mdb_matrix_d.h:1611:
/usr/local/include/gsl/gsl_cblas.h:46:6: error: redefinition of 'CBLAS_ORDER'
enum CBLAS_ORDER {CblasRowMajor=101, CblasColMajor=102};
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/cblas.h:34:8: note:
previous definition is here
enum CBLAS_ORDER {CblasRowMajor=101, CblasColMajor=102 };